/** Represents a single question generated by a topic module. */
export interface Question{
	id: string;
	topicId: string;
	topicName: string;
	text: string;
	answer: string;
	answerType: "numeric"|"expression"|"string";
	unit?: string;
	choices?: string[];
	difficulty: "easy"|"medium"|"hard";
	questionType: "MC"|"MR"|"TBR"|"LAB"|"QQT";
}

/** Configuration for the question generator (difficulty, MCQ mode, etc.). */
export interface GenerateOptions{
	difficulty: "easy"|"medium"|"hard";
	forceMcq?: boolean;
	seed?: number;
}

/** Function signature for a topic-specific generator. */
export type GeneratorFn=(options: GenerateOptions)=>Question;

/** Registry mapping topic IDs to their generator functions. */
export interface GeneratorRegistry{
	[key: string]: GeneratorFn;
}

/** User settings persisted in localStorage. */
export interface AppSettings{
	theme: "light"|"dark"|"system";
	defaultMode: "single"|"mental";
	autoContinue: boolean;
	shuffle: boolean;
	defaultScope: string;
	notifications: boolean;
	difficulty: "easy"|"medium"|"hard";
	timerSeconds: number;
	maxQuestions: number;
	autoCheckDelayMs: number;
	decimalPlaces: number;
	sound: boolean;
	vibration: boolean;
	mcqChoices: number;
	performanceMode: boolean;
	waveBackground: boolean;
	blurEffect: boolean;
}

/** State of a mental mode session. */
export interface MentalSession{
	active: boolean;
	paused: boolean;
	score: number;
	total: number;
	timeLeft: number;
	timerInterval: number|null;
	questionsRemaining: number;
	unlimited: boolean;
	startTime: number;
}

/** Structure for a seeded pseudo-random number generator. */
export interface SeededRandom{
	nextInt(min: number, max: number): number;
	nextFloat(): number;
	choice<T>(arr: T[]): T;
}